version: '3.8'
services:
  postgres:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  node:
    build: .
    container_name: node_app_container
    ports:
      - 5004:5004
    platform: linux/x86_64
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
